name: discord_server
description: Enterprise communication platform backend built with Serverpod.
version: 1.0.0
homepage: https://github.com/felipemacedo1/discord_open

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  serverpod: 2.6.0
  serverpod_auth_server: 2.6.0
  livekit_server_sdk: 1.0.1

dev_dependencies:
  lints: ">=3.0.0 <6.0.0"
  test: "^1.24.2"
  serverpod_test: 2.6.0
